# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: |
    TEST="abcd"
    T1="zx"
  displayName: 'This is my variable'

- bash: |
    echo "$(TEST)"
    echo "hello"
    echo "$TEST"
    echo "t1"
    echo "$T1"
  displayName: "print my variable"
  
